/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_michaelszm_ndkpractise_NdkCppInterface */

#ifndef _Included_com_example_michaelszm_ndkpractise_NdkCppInterface
#define _Included_com_example_michaelszm_ndkpractise_NdkCppInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    TestConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_TestConst
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    testPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_testPointer
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    testConstReference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_testConstReference
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    inlineFuncTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_inlineFuncTest
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    funcPointerTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_funcPointerTest
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    cppClassTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_cppClassTest
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    testConstructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_testConstructor
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    testDestruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_testDestruct
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    testCopyFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_testCopyFunc
        (JNIEnv *, jobject);

/*
 * Class:     com_example_michaelszm_ndkpractise_NdkCppInterface
 * Method:    testCopyFuncScence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_michaelszm_ndkpractise_NdkCppInterface_testCopyFuncScence
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
